version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      production:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      development:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
