class PostgresContainer:
    def __init__(self, image: str, *, driver: str | None = None) -> None: ...
    def start(self) -> PostgresContainer: ...
    def stop(self) -> None: ...
    def get_connection_url(self) -> str: ...
